In [ ]:
# BugSight AI

## Phase 1 – Data Collection

#Objective:
#Load the raw bug dataset, inspect its structure, and prepare it for exploratory data analysis.

In [3]:
import pandas as pd
import numpy as np

In [10]:
import os

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
c:\Users\Ahana Arora\OneDrive\Pictures\Documents\AI-Bug-Severity-Predictor\ml\notebooks

In [11]:
print("\nFiles in current folder:")
print(os.listdir())

Files in current folder:
['01_Data_Collection.ipynb', '01_EDA.ipynb', '02_Preprocessing.ipynb', '03_Feature_Engineering.ipynb', 'label_encoder.pkl']

In [13]:

import os

print(os.listdir(".."))

['notebooks', 'src']

In [16]:
print(os.listdir("../.."))

['.git', '.github', '.gitignore', 'backend', 'data', 'docs', 'frontend', 'ml', 'models', 'monitoring', 'README.md', 'requirements.txt', 'tests', 'venv']

In [17]:
import os

print(os.listdir("../../data"))

['processed', 'raw']

In [18]:
print(os.listdir("../../data/raw"))

['changelog.csv', 'comments.csv', 'issuelinks.csv', 'issues.csv']

In [19]:
print(os.listdir("../../data"))

['processed', 'raw']

In [21]:
print(os.listdir("../../data/raw"))

['changelog.csv', 'comments.csv', 'issuelinks.csv', 'issues.csv']

In [24]:
import pandas as pd

df = pd.read_csv(
    "../../data/raw/issues.csv",
    low_memory=False
)

In [25]:
df.head()

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,...,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
0,12451174.0,WW-712,Update config browser to work with the new syntax,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,...,WW,Struts 2,10380.0,struts.apache.org,Struts Framework,2005-01-01 07:50:46,0.0,2005-01-01 07:47:50,2005-01-01 07:50:46,The config browser used Velocity calling the t...
1,29159.0,XALANC-446,XALAN_C 1.9 or current do not build on Fedora ...,1.0,A fix for this issue is checked into the tree ...,Fixed,1.0,Blocker,[],NaN,...,XALANC,XalanC,11460.0,Xalan Related Projects,Xalan,2004-12-30 05:30:36,1.0,2004-12-25 22:50:30,2005-01-01 10:20:52,Two types of errors:\n1- runConfigure and conf...
2,12420130.0,ROL-587,"Problem with ADD new post, and DELETE post.",5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,2.0,Critical,[],4d4054ac,...,ROL,Apache Roller,10331.0,NaN,Roller,2005-01-02 15:21:00,0.0,2005-01-01 13:52:46,2005-01-02 15:21:00,"When trying to add new post, I was getting nex..."
3,29222.0,AXIS-1741,LogHandler can only work in GlobalConfiguratio...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,0.0,2005-01-02 19:13:37,2005-01-02 19:35:36,org.apache.axis.handlers.LogHandler in request...
4,29233.0,AXIS-1745,Decoding of service is broken in org.apache.ax...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,1.0,2005-01-03 03:34:52,2005-01-03 03:34:52,The following code assumes a lot of things:\n\...

In [26]:
print("Dataset Shape:", df.shape)

Dataset Shape: (1149323, 37)

In [27]:
print(df.columns)

Index(['id', 'key', 'summary', 'resolution.id', 'resolution.description',
       'resolution.name', 'priority.id', 'priority.name', 'labels', 'assignee',
       'status.id', 'status.description', 'status.name', 'statusCategory.id',
       'statusCategory.key', 'statusCategory.colorName', 'statusCategory.name',
       'customfield_12310921', 'creator', 'subtasks', 'reporter',
       'votes.votes', 'issuetype.id', 'issuetype.description',
       'issuetype.name', 'issuetype.subtask', 'project.id', 'project.key',
       'project.name', 'projectCategory.id', 'projectCategory.description',
       'projectCategory.name', 'resolutiondate', 'watches.watchCount',
       'created', 'updated', 'description'],
      dtype='str')

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149323 entries, 0 to 1149322
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   id                           1131224 non-null  float64
 1   key                          1149323 non-null  str
 2   summary                      1131223 non-null  str
 3   resolution.id                946655 non-null   float64
 4   resolution.description       928770 non-null   str
 5   resolution.name              946655 non-null   str
 6   priority.id                  1117464 non-null  float64
 7   priority.name                1117464 non-null  str
 8   labels                       1131004 non-null  str
 9   assignee                     780217 non-null   str
 10  status.id                    1131224 non-null  float64
 11  status.description           1123393 non-null  str
 12  status.name                  1131224 non-null  str
 13  statusCategory.id            1131224 non-null  float64
 14  statusCategory.key           1131224 non-null  str
 15  statusCategory.colorName     1131224 non-null  str
 16  statusCategory.name          1131224 non-null  str
 17  customfield_12310921         15834 non-null    str
 18  creator                      1127737 non-null  str
 19  subtasks                     1131224 non-null  str
 20  reporter                     1130088 non-null  str
 21  votes.votes                  1131224 non-null  float64
 22  issuetype.id                 1131224 non-null  float64
 23  issuetype.description        1130064 non-null  str
 24  issuetype.name               1131224 non-null  str
 25  issuetype.subtask            1131224 non-null  object
 26  project.id                   1131224 non-null  float64
 27  project.key                  1131224 non-null  str
 28  project.name                 1131224 non-null  str
 29  projectCategory.id           1049679 non-null  float64
 30  projectCategory.description  926376 non-null   str
 31  projectCategory.name         1049679 non-null  str
 32  resolutiondate               946715 non-null   str
 33  watches.watchCount           1131224 non-null  float64
 34  created                      1131224 non-null  str
 35  updated                      1131224 non-null  str
 36  description                  1026080 non-null  str
dtypes: float64(10), object(1), str(26)
memory usage: 324.4+ MB

In [29]:
print(df.isnull().sum())

id                               18099
key                                  0
summary                          18100
resolution.id                   202668
resolution.description          220553
resolution.name                 202668
priority.id                      31859
priority.name                    31859
labels                           18319
assignee                        369106
status.id                        18099
status.description               25930
status.name                      18099
statusCategory.id                18099
statusCategory.key               18099
statusCategory.colorName         18099
statusCategory.name              18099
customfield_12310921           1133489
creator                          21586
subtasks                         18099
reporter                         19235
votes.votes                      18099
issuetype.id                     18099
issuetype.description            19259
issuetype.name                   18099
issuetype.subtask                18099
project.id                       18099
project.key                      18099
project.name                     18099
projectCategory.id               99644
projectCategory.description     222947
projectCategory.name             99644
resolutiondate                  202608
watches.watchCount               18099
created                          18099
updated                          18099
description                     123243
dtype: int64

In [30]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 1995

In [31]:
df.describe(include="all")

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,...,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
count,1.131224e+06,1149323,1131223,946655.000000,928770,946655,1.117464e+06,1117464,1131004,780217,...,1131224,1131224,1.049679e+06,926376,1049679,946715,1.131224e+06,1131224,1131224,1026080
unique,NaN,1140013,1105168,NaN,21,23,NaN,15,27173,28375,...,640,640,NaN,143,163,903089,NaN,1115924,848225,1006177
top,NaN,HADOOP-6216,Please delete old releases from mirroring system,NaN,A fix for this issue is checked into the tree ...,Fixed,NaN,Major,[],06893fff,...,SPARK,Spark,NaN,Scalable Distributed Computing,Hadoop,2005-10-05 18:48:46,NaN,2014-01-15 01:18:15,2024-02-27 23:24:02,<no value>
freq,NaN,5,173,NaN,720175,720175,NaN,746289,927997,14916,...,49833,49833,NaN,118392,118392,869,NaN,26,192,118
mean,1.277000e+07,NaN,NaN,236.968574,NaN,NaN,3.463777e+02,NaN,NaN,NaN,...,NaN,NaN,1.173169e+04,NaN,NaN,NaN,2.085979e+00,NaN,NaN,NaN
std,1.492686e+06,NaN,NaN,1517.074689,NaN,NaN,1.825288e+03,NaN,NaN,NaN,...,NaN,NaN,1.927300e+03,NaN,NaN,NaN,2.671289e+00,NaN,NaN,NaN
min,1.001200e+04,NaN,NaN,1.000000,NaN,NaN,1.000000e+00,NaN,NaN,NaN,...,NaN,NaN,1.002000e+04,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN
25%,1.260087e+07,NaN,NaN,1.000000,NaN,NaN,3.000000e+00,NaN,NaN,NaN,...,NaN,NaN,1.026000e+04,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN
50%,1.292847e+07,NaN,NaN,1.000000,NaN,NaN,3.000000e+00,NaN,NaN,NaN,...,NaN,NaN,1.048000e+04,NaN,NaN,NaN,2.000000e+00,NaN,NaN,NaN
75%,1.323934e+07,NaN,NaN,1.000000,NaN,NaN,4.000000e+00,NaN,NaN,NaN,...,NaN,NaN,1.346000e+04,NaN,NaN,NaN,3.000000e+00,NaN,NaN,NaN
max,1.359793e+07,NaN,NaN,10101.000000,NaN,NaN,1.020000e+04,NaN,NaN,NaN,...,NaN,NaN,1.666200e+04,NaN,NaN,NaN,2.400000e+02,NaN,NaN,NaN