In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [9]:
# Load the dataset
df = pd.read_csv("../../data/raw/issues.csv", low_memory=False)

In [10]:
df.head()

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,status.id,status.description,status.name,statusCategory.id,statusCategory.key,statusCategory.colorName,statusCategory.name,customfield_12310921,creator,subtasks,reporter,votes.votes,issuetype.id,issuetype.description,issuetype.name,issuetype.subtask,project.id,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
0,12451174.0,WW-712,Update config browser to work with the new syntax,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,6.0,"The issue is considered finished, the resoluti...",Closed,3.0,done,green,Done,NaN,632ec9dd,[],632ec9dd,0.0,4.0,An improvement or enhancement to an existing f...,Improvement,False,12311041.0,WW,Struts 2,10380.0,struts.apache.org,Struts Framework,2005-01-01 07:50:46,0.0,2005-01-01 07:47:50,2005-01-01 07:50:46,The config browser used Velocity calling the t...
1,29159.0,XALANC-446,XALAN_C 1.9 or current do not build on Fedora ...,1.0,A fix for this issue is checked into the tree ...,Fixed,1.0,Blocker,[],NaN,5.0,"A resolution has been taken, and it is awaitin...",Resolved,3.0,done,green,Done,NaN,4fc0930d,[],4fc0930d,0.0,1.0,A problem which impairs or prevents the functi...,Bug,False,10582.0,XALANC,XalanC,11460.0,Xalan Related Projects,Xalan,2004-12-30 05:30:36,1.0,2004-12-25 22:50:30,2005-01-01 10:20:52,Two types of errors:\n1- runConfigure and conf...
2,12420130.0,ROL-587,"Problem with ADD new post, and DELETE post.",5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,2.0,Critical,[],4d4054ac,6.0,"The issue is considered finished, the resoluti...",Closed,3.0,done,green,Done,NaN,110153ae,[],110153ae,0.0,1.0,A problem which impairs or prevents the functi...,Bug,False,12310906.0,ROL,Apache Roller,10331.0,NaN,Roller,2005-01-02 15:21:00,0.0,2005-01-01 13:52:46,2005-01-02 15:21:00,"When trying to add new post, I was getting nex..."
3,29222.0,AXIS-1741,LogHandler can only work in GlobalConfiguratio...,NaN,NaN,NaN,3.0,Major,[],NaN,1.0,The issue is open and ready for the assignee t...,Open,2.0,new,blue-gray,To Do,NaN,be1c6b12,[],be1c6b12,0.0,1.0,A problem which impairs or prevents the functi...,Bug,False,10460.0,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,0.0,2005-01-02 19:13:37,2005-01-02 19:35:36,org.apache.axis.handlers.LogHandler in request...
4,29233.0,AXIS-1745,Decoding of service is broken in org.apache.ax...,NaN,NaN,NaN,3.0,Major,[],NaN,1.0,The issue is open and ready for the assignee t...,Open,2.0,new,blue-gray,To Do,NaN,97843411,[],97843411,0.0,1.0,A problem which impairs or prevents the functi...,Bug,False,10460.0,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,1.0,2005-01-03 03:34:52,2005-01-03 03:34:52,The following code assumes a lot of things:\n\...

In [11]:
df.shape

(1149323, 37)

In [12]:
df.columns.tolist()

['id',
 'key',
 'summary',
 'resolution.id',
 'resolution.description',
 'resolution.name',
 'priority.id',
 'priority.name',
 'labels',
 'assignee',
 'status.id',
 'status.description',
 'status.name',
 'statusCategory.id',
 'statusCategory.key',
 'statusCategory.colorName',
 'statusCategory.name',
 'customfield_12310921',
 'creator',
 'subtasks',
 'reporter',
 'votes.votes',
 'issuetype.id',
 'issuetype.description',
 'issuetype.name',
 'issuetype.subtask',
 'project.id',
 'project.key',
 'project.name',
 'projectCategory.id',
 'projectCategory.description',
 'projectCategory.name',
 'resolutiondate',
 'watches.watchCount',
 'created',
 'updated',
 'description']

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1149323 entries, 0 to 1149322
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   id                           1131224 non-null  float64
 1   key                          1149323 non-null  str
 2   summary                      1131223 non-null  str
 3   resolution.id                946655 non-null   float64
 4   resolution.description       928770 non-null   str
 5   resolution.name              946655 non-null   str
 6   priority.id                  1117464 non-null  float64
 7   priority.name                1117464 non-null  str
 8   labels                       1131004 non-null  str
 9   assignee                     780217 non-null   str
 10  status.id                    1131224 non-null  float64
 11  status.description           1123393 non-null  str
 12  status.name                  1131224 non-null  str
 13  statusCategory.id            1131224 non-null  float64
 14  statusCategory.key           1131224 non-null  str
 15  statusCategory.colorName     1131224 non-null  str
 16  statusCategory.name          1131224 non-null  str
 17  customfield_12310921         15834 non-null    str
 18  creator                      1127737 non-null  str
 19  subtasks                     1131224 non-null  str
 20  reporter                     1130088 non-null  str
 21  votes.votes                  1131224 non-null  float64
 22  issuetype.id                 1131224 non-null  float64
 23  issuetype.description        1130064 non-null  str
 24  issuetype.name               1131224 non-null  str
 25  issuetype.subtask            1131224 non-null  object
 26  project.id                   1131224 non-null  float64
 27  project.key                  1131224 non-null  str
 28  project.name                 1131224 non-null  str
 29  projectCategory.id           1049679 non-null  float64
 30  projectCategory.description  926376 non-null   str
 31  projectCategory.name         1049679 non-null  str
 32  resolutiondate               946715 non-null   str
 33  watches.watchCount           1131224 non-null  float64
 34  created                      1131224 non-null  str
 35  updated                      1131224 non-null  str
 36  description                  1026080 non-null  str
dtypes: float64(10), object(1), str(26)
memory usage: 324.4+ MB

In [14]:
df.describe(include="all")

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,status.id,status.description,status.name,statusCategory.id,statusCategory.key,statusCategory.colorName,statusCategory.name,customfield_12310921,creator,subtasks,reporter,votes.votes,issuetype.id,issuetype.description,issuetype.name,issuetype.subtask,project.id,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
count,1.131224e+06,1149323,1131223,946655.000000,928770,946655,1.117464e+06,1117464,1131004,780217,1.131224e+06,1123393,1131224,1.131224e+06,1131224,1131224,1131224,15834,1127737,1131224,1130088,1.131224e+06,1.131224e+06,1130064,1131224,1131224,1.131224e+06,1131224,1131224,1.049679e+06,926376,1049679,946715,1.131224e+06,1131224,1131224,1026080
unique,NaN,1140013,1105168,NaN,21,23,NaN,15,27173,28375,NaN,17,28,NaN,3,3,3,1808,147811,15325,148698,NaN,NaN,26,40,2,NaN,640,640,NaN,143,163,903089,NaN,1115924,848225,1006177
top,NaN,HADOOP-6216,Please delete old releases from mirroring system,NaN,A fix for this issue is checked into the tree ...,Fixed,NaN,Major,[],06893fff,NaN,"The issue is considered finished, the resoluti...",Closed,NaN,done,green,Done,"[""com.atlassian.greenhopper.service.sprint.Spr...",1595b58c,[],1595b58c,NaN,NaN,A problem which impairs or prevents the functi...,Bug,False,NaN,SPARK,Spark,NaN,Scalable Distributed Computing,Hadoop,2005-10-05 18:48:46,NaN,2014-01-15 01:18:15,2024-02-27 23:24:02,<no value>
freq,NaN,5,173,NaN,720175,720175,NaN,746289,927997,14916,NaN,510938,510938,NaN,947214,947214,947214,1002,17436,1115764,17436,NaN,NaN,566872,566872,1028222,NaN,49833,49833,NaN,118392,118392,869,NaN,26,192,118
mean,1.277000e+07,NaN,NaN,236.968574,NaN,NaN,3.463777e+02,NaN,NaN,NaN,1.330470e+02,NaN,NaN,2.860182e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.025456e-01,1.605977e+01,NaN,NaN,NaN,1.160891e+07,NaN,NaN,1.173169e+04,NaN,NaN,NaN,2.085979e+00,NaN,NaN,NaN
std,1.492686e+06,NaN,NaN,1517.074689,NaN,NaN,1.825288e+03,NaN,NaN,NaN,1.130184e+03,NaN,NaN,3.783060e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.946615e-01,3.859894e+02,NaN,NaN,NaN,2.859650e+06,NaN,NaN,1.927300e+03,NaN,NaN,NaN,2.671289e+00,NaN,NaN,NaN
min,1.001200e+04,NaN,NaN,1.000000,NaN,NaN,1.000000e+00,NaN,NaN,NaN,1.000000e+00,NaN,NaN,2.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1.000000e+00,NaN,NaN,NaN,1.001200e+04,NaN,NaN,1.002000e+04,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN
25%,1.260087e+07,NaN,NaN,1.000000,NaN,NaN,3.000000e+00,NaN,NaN,NaN,5.000000e+00,NaN,NaN,3.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1.000000e+00,NaN,NaN,NaN,1.231075e+07,NaN,NaN,1.026000e+04,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN
50%,1.292847e+07,NaN,NaN,1.000000,NaN,NaN,3.000000e+00,NaN,NaN,NaN,5.000000e+00,NaN,NaN,3.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1.000000e+00,NaN,NaN,NaN,1.231202e+07,NaN,NaN,1.048000e+04,NaN,NaN,NaN,2.000000e+00,NaN,NaN,NaN
75%,1.323934e+07,NaN,NaN,1.000000,NaN,NaN,4.000000e+00,NaN,NaN,NaN,6.000000e+00,NaN,NaN,3.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,4.000000e+00,NaN,NaN,NaN,1.231592e+07,NaN,NaN,1.346000e+04,NaN,NaN,NaN,3.000000e+00,NaN,NaN,NaN
max,1.359793e+07,NaN,NaN,10101.000000,NaN,NaN,1.020000e+04,NaN,NaN,NaN,1.112100e+04,NaN,NaN,4.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.100000e+02,1.150000e+04,NaN,NaN,NaN,1.232552e+07,NaN,NaN,1.666200e+04,NaN,NaN,NaN,2.400000e+02,NaN,NaN,NaN

In [15]:
# Check missing values
missing_values = df.isnull().sum().sort_values(ascending=False)

missing_values

customfield_12310921           1133489
assignee                        369106
projectCategory.description     222947
resolution.description          220553
resolution.id                   202668
resolution.name                 202668
resolutiondate                  202608
description                     123243
projectCategory.id               99644
projectCategory.name             99644
priority.id                      31859
priority.name                    31859
status.description               25930
creator                          21586
issuetype.description            19259
reporter                         19235
labels                           18319
summary                          18100
id                               18099
subtasks                         18099
status.id                        18099
project.name                     18099
statusCategory.key               18099
statusCategory.colorName         18099
statusCategory.name              18099
statusCategory.id                18099
status.name                      18099
issuetype.id                     18099
votes.votes                      18099
issuetype.name                   18099
project.key                      18099
project.id                       18099
issuetype.subtask                18099
created                          18099
watches.watchCount               18099
updated                          18099
key                                  0
dtype: int64

In [16]:
# Check duplicate rows
df.duplicated().sum()

np.int64(1995)

In [17]:
# Check data types
df.dtypes

id                             float64
key                                str
summary                            str
resolution.id                  float64
resolution.description             str
resolution.name                    str
priority.id                    float64
priority.name                      str
labels                             str
assignee                           str
status.id                      float64
status.description                 str
status.name                        str
statusCategory.id              float64
statusCategory.key                 str
statusCategory.colorName           str
statusCategory.name                str
customfield_12310921               str
creator                            str
subtasks                           str
reporter                           str
votes.votes                    float64
issuetype.id                   float64
issuetype.description              str
issuetype.name                     str
issuetype.subtask               object
project.id                     float64
project.key                        str
project.name                       str
projectCategory.id             float64
projectCategory.description        str
projectCategory.name               str
resolutiondate                     str
watches.watchCount             float64
created                            str
updated                            str
description                        str
dtype: object

In [18]:
# Count unique values in each column
df.nunique().sort_values()

issuetype.subtask                    2
statusCategory.colorName             3
statusCategory.key                   3
statusCategory.id                    3
statusCategory.name                  3
priority.id                         15
priority.name                       15
status.description                  17
resolution.description              21
resolution.id                       23
resolution.name                     23
issuetype.description               26
status.name                         28
status.id                           28
issuetype.id                        40
issuetype.name                      40
votes.votes                         76
watches.watchCount                 125
projectCategory.description        143
projectCategory.name               163
projectCategory.id                 163
project.key                        640
project.name                       640
project.id                         640
customfield_12310921              1808
subtasks                         15325
labels                           27173
assignee                         28375
creator                         147811
reporter                        148698
updated                         848225
resolutiondate                  903089
description                    1006177
summary                        1105168
created                        1115924
id                             1121914
key                            1140013
dtype: int64

In [19]:
# Display all column names
df.columns.tolist()

['id',
 'key',
 'summary',
 'resolution.id',
 'resolution.description',
 'resolution.name',
 'priority.id',
 'priority.name',
 'labels',
 'assignee',
 'status.id',
 'status.description',
 'status.name',
 'statusCategory.id',
 'statusCategory.key',
 'statusCategory.colorName',
 'statusCategory.name',
 'customfield_12310921',
 'creator',
 'subtasks',
 'reporter',
 'votes.votes',
 'issuetype.id',
 'issuetype.description',
 'issuetype.name',
 'issuetype.subtask',
 'project.id',
 'project.key',
 'project.name',
 'projectCategory.id',
 'projectCategory.description',
 'projectCategory.name',
 'resolutiondate',
 'watches.watchCount',
 'created',
 'updated',
 'description']

In [20]:
df.columns.tolist()

['id',
 'key',
 'summary',
 'resolution.id',
 'resolution.description',
 'resolution.name',
 'priority.id',
 'priority.name',
 'labels',
 'assignee',
 'status.id',
 'status.description',
 'status.name',
 'statusCategory.id',
 'statusCategory.key',
 'statusCategory.colorName',
 'statusCategory.name',
 'customfield_12310921',
 'creator',
 'subtasks',
 'reporter',
 'votes.votes',
 'issuetype.id',
 'issuetype.description',
 'issuetype.name',
 'issuetype.subtask',
 'project.id',
 'project.key',
 'project.name',
 'projectCategory.id',
 'projectCategory.description',
 'projectCategory.name',
 'resolutiondate',
 'watches.watchCount',
 'created',
 'updated',
 'description']

In [21]:
df.columns.tolist()

['id',
 'key',
 'summary',
 'resolution.id',
 'resolution.description',
 'resolution.name',
 'priority.id',
 'priority.name',
 'labels',
 'assignee',
 'status.id',
 'status.description',
 'status.name',
 'statusCategory.id',
 'statusCategory.key',
 'statusCategory.colorName',
 'statusCategory.name',
 'customfield_12310921',
 'creator',
 'subtasks',
 'reporter',
 'votes.votes',
 'issuetype.id',
 'issuetype.description',
 'issuetype.name',
 'issuetype.subtask',
 'project.id',
 'project.key',
 'project.name',
 'projectCategory.id',
 'projectCategory.description',
 'projectCategory.name',
 'resolutiondate',
 'watches.watchCount',
 'created',
 'updated',
 'description']

In [22]:
df["priority.name"].value_counts()

priority.name
Major             746289
Minor             216620
Critical           49514
Blocker            36476
Trivial            30399
Normal             13556
Low                 6829
P2                  6781
P3                  6372
Not a Priority      2365
P1                   838
Urgent               676
P4                   298
P0                   274
High                 177
Name: count, dtype: int64

In [23]:
important_columns = [
    "summary",
    "description",
    "priority.name",
    "issuetype.name",
    "status.name",
    "resolution.name"
]

df[important_columns].isnull().sum()

summary             18100
description        123243
priority.name       31859
issuetype.name      18099
status.name         18099
resolution.name    202668
dtype: int64

In [24]:
df_ml = df[
    [
        "summary",
        "description",
        "priority.name",
        "issuetype.name",
        "status.name",
        "resolution.name"
    ]
]

In [25]:
df_ml.head()

,summary,description,priority.name,issuetype.name,status.name,resolution.name
0,Update config browser to work with the new syntax,The config browser used Velocity calling the t...,Minor,Improvement,Closed,Fixed
1,XALAN_C 1.9 or current do not build on Fedora ...,Two types of errors:\n1- runConfigure and conf...,Blocker,Bug,Resolved,Fixed
2,"Problem with ADD new post, and DELETE post.","When trying to add new post, I was getting nex...",Critical,Bug,Closed,Cannot Reproduce
3,LogHandler can only work in GlobalConfiguratio...,org.apache.axis.handlers.LogHandler in request...,Major,Bug,Open,NaN
4,Decoding of service is broken in org.apache.ax...,The following code assumes a lot of things:\n\...,Major,Bug,Open,NaN

In [26]:
df_ml.shape

(1149323, 6)

In [27]:
df_ml.to_csv("../../data/processed/issues_cleaned.csv", index=False)

In [28]:
pd.read_csv("../../data/processed/issues_cleaned.csv").head()

,summary,description,priority.name,issuetype.name,status.name,resolution.name
0,Update config browser to work with the new syntax,The config browser used Velocity calling the t...,Minor,Improvement,Closed,Fixed
1,XALAN_C 1.9 or current do not build on Fedora ...,Two types of errors:\n1- runConfigure and conf...,Blocker,Bug,Resolved,Fixed
2,"Problem with ADD new post, and DELETE post.","When trying to add new post, I was getting nex...",Critical,Bug,Closed,Cannot Reproduce
3,LogHandler can only work in GlobalConfiguratio...,org.apache.axis.handlers.LogHandler in request...,Major,Bug,Open,NaN
4,Decoding of service is broken in org.apache.ax...,The following code assumes a lot of things:\n\...,Major,Bug,Open,NaN

In [29]:
# Select only the columns required for our project

df_clean = df[[
    "summary",
    "description",
    "priority.name",
    "status.name",
    "resolution.name",
    "issuetype.name"
]].copy()

df_clean.head()

,summary,description,priority.name,status.name,resolution.name,issuetype.name
0,Update config browser to work with the new syntax,The config browser used Velocity calling the t...,Minor,Closed,Fixed,Improvement
1,XALAN_C 1.9 or current do not build on Fedora ...,Two types of errors:\n1- runConfigure and conf...,Blocker,Resolved,Fixed,Bug
2,"Problem with ADD new post, and DELETE post.","When trying to add new post, I was getting nex...",Critical,Closed,Cannot Reproduce,Bug
3,LogHandler can only work in GlobalConfiguratio...,org.apache.axis.handlers.LogHandler in request...,Major,Open,NaN,Bug
4,Decoding of service is broken in org.apache.ax...,The following code assumes a lot of things:\n\...,Major,Open,NaN,Bug

In [30]:
df_clean.isnull().sum()

summary             18100
description        123243
priority.name       31859
status.name         18099
resolution.name    202668
issuetype.name      18099
dtype: int64

In [31]:
df_clean["summary"] = df_clean["summary"].fillna("")
df_clean["description"] = df_clean["description"].fillna("")
df_clean["priority.name"] = df_clean["priority.name"].fillna("Unknown")
df_clean["status.name"] = df_clean["status.name"].fillna("Unknown")
df_clean["resolution.name"] = df_clean["resolution.name"].fillna("Unknown")
df_clean["issuetype.name"] = df_clean["issuetype.name"].fillna("Unknown")

In [32]:
df_clean.to_csv("../../data/processed/issues_cleaned.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [33]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"<.*?>", " ", text)        # remove HTML
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)  # remove special chars
    text = re.sub(r"\s+", " ", text).strip()   # remove extra spaces
    return text

In [34]:
df_ml["summary"] = df_ml["summary"].apply(clean_text)
df_ml["description"] = df_ml["description"].apply(clean_text)

In [35]:
df_ml["text"] = df_ml["summary"] + " " + df_ml["description"]

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_ml["target"] = le.fit_transform(df_ml["priority.name"])

In [37]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Blocker': np.int64(0),
 'Critical': np.int64(1),
 'High': np.int64(2),
 'Low': np.int64(3),
 'Major': np.int64(4),
 'Minor': np.int64(5),
 'Normal': np.int64(6),
 'Not a Priority': np.int64(7),
 'P0': np.int64(8),
 'P1': np.int64(9),
 'P2': np.int64(10),
 'P3': np.int64(11),
 'P4': np.int64(12),
 'Trivial': np.int64(13),
 'Urgent': np.int64(14),
 nan: np.int64(15)}

In [38]:
final_df = df_ml[["text", "target"]]

In [39]:
from sklearn.model_selection import train_test_split

X = final_df["text"]
y = final_df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [40]:
y.value_counts()

target
4     746289
5     216620
1      49514
0      36476
15     31859
13     30399
6      13556
3       6829
10      6781
11      6372
7       2365
9        838
14       676
12       298
8        274
2        177
Name: count, dtype: int64

In [44]:
final_df.shape

(1149323, 2)

In [42]:
y.value_counts()

target
4     746289
5     216620
1      49514
0      36476
15     31859
13     30399
6      13556
3       6829
10      6781
11      6372
7       2365
9        838
14       676
12       298
8        274
2        177
Name: count, dtype: int64

In [45]:
final_df.head()

                                                text  target
0  update config browser to work with the new syn...       5
1  xalan c 1 9 or current do not build on fedora ...       0
2  problem with add new post and delete post when...       1
3  loghandler can only work in globalconfiguratio...       4
4  decoding of service is broken in org apache ax...       4